env:
  - "DB=mysql BUNDLE_WITHOUT=postgresql:sqlite"
  - "DB=postgresql BUNDLE_WITHOUT=mysql:sqlite"
  - "DB=sqlite BUNDLE_WITHOUT=postgresql:mysql"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake --trace fulcrum:setup db:setup"
rvm:
  - 1.9.3
  - 2.0.0
script:
  - "bundle exec rake travis"
